# Site settings
title: Carina Boo
header-img: img/home-bg.jpg
email: carinaboo@berkeley.edu
description: "Designer, developer, and lifelong learner"
baseurl: ""
url: "http://carinaboo.github.io/"
twitter_username: carinaboo
github_username:  carinaboo
facebook_username:  carina.boo
linkedin_username:  carinaboo

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
